packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: true
patchedDependencies:
  '@phosphor-icons/react': patches/@phosphor-icons__react.patch
  'next-themes@0.4.6': patches/next-themes@0.4.6.patch
