"""Public, unauthenticated endpoints for the marketing + login surfaces.

These are explicitly carved out from the rest of the app:

- `GET /public/projects-map` — anonymized, aggregated project locations
  for the pre-login NL map. RLS is bypassed (the request has no tenant
  context); we only return city / averaged lat-lng / count so no tenant
  data leaks.

- `GET /public/system-status` — live platform health for the login page
  status badge and KPI strip. Pings DB + Redis + MinIO HEAD; degrades on
  the first failure but always returns a payload so the page never errors.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, Depends, Response
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

from bimdossier_api.approx import approx_count_floor
from bimdossier_api.cache.client import get_redis
from bimdossier_api.config import Settings, get_settings
from bimdossier_api.db import get_async_session
from bimdossier_api.models.blog_post import BlogPost, BlogPostStatus
from bimdossier_api.models.organization import Organization, OrganizationStatus
from bimdossier_api.routers.admin_blog import _fetch_content
from bimdossier_api.schemas.blog import BLOG_LOCALES, BlogPostPublicRead
from bimdossier_api.schemas.public import (
    ProjectsMapPoint,
    SystemStatusResponse,
)
from bimdossier_api.storage import StorageBackend, get_attachments_bucket, get_storage

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/public", tags=["public"])


@router.get("/projects-map", response_model=list[ProjectsMapPoint])
async def projects_map(
    response: Response,
    session: AsyncSession = Depends(get_async_session),
) -> list[ProjectsMapPoint]:
    """Aggregate non-removed, geo-located projects by city across all tenants.

    Pre-login endpoint with no tenant context. Under schema-per-tenant the
    rows live in `org_<hex>.projects`, so we UNION ALL the geo columns from
    every active org schema and aggregate in an outer query. Only anonymized
    fields cross the wire (city + averaged lat/lng + floored count).

    `lifecycle_state` is a per-schema enum type; we filter it inside each
    subquery and project only schema-agnostic columns so the UNION's column
    types unify cleanly. Per-city counts are floored to one significant
    figure via `approx_count_floor` so exact tenant numbers never leak.
    Cached for one minute at the CDN edge.
    """
    schemas_stmt = select(Organization.schema_name).where(
        Organization.status.in_(
            (OrganizationStatus.active, OrganizationStatus.suspended)
        ),
        Organization.deleted_at.is_(None),
    )
    schemas = (await session.execute(schemas_stmt)).scalars().all()

    response.headers["Cache-Control"] = "public, max-age=60"
    if not schemas:
        return []

    # schema_name is generated by schema_name_for() as `org_<32 hex>` — not
    # user input, safe to interpolate.
    union_parts = [
        f'SELECT city, latitude, longitude, id FROM "{s}".projects '
        f"WHERE lifecycle_state <> 'removed' "
        f"AND latitude IS NOT NULL AND longitude IS NOT NULL AND city IS NOT NULL"
        for s in schemas
    ]
    sql = (
        "SELECT city, AVG(latitude) AS lat, AVG(longitude) AS lng, "
        "COUNT(id) AS count FROM ("
        + " UNION ALL ".join(union_parts)
        + ") AS all_projects GROUP BY city"
    )
    rows = (await session.execute(text(sql))).all()
    return [
        ProjectsMapPoint(
            city=row.city,
            lat=float(row.lat),
            lng=float(row.lng),
            count=approx_count_floor(int(row.count)),
        )
        for row in rows
    ]


async def _check_db(session: AsyncSession) -> bool:
    try:
        await session.execute(select(1))
        return True
    except Exception:
        logger.warning("system-status DB check failed", exc_info=True)
        return False


async def _check_redis() -> bool:
    try:
        await get_redis().ping()
        return True
    except Exception:
        logger.warning("system-status Redis check failed", exc_info=True)
        return False


async def _check_storage() -> bool:
    try:
        await get_storage().ensure_bucket()
        return True
    except Exception:
        logger.warning("system-status storage check failed", exc_info=True)
        return False


@router.get("/system-status", response_model=SystemStatusResponse)
async def system_status(
    session: AsyncSession = Depends(get_async_session),
    settings: Settings = Depends(get_settings),
) -> SystemStatusResponse:
    checks = {
        "db": await _check_db(session),
        "redis": await _check_redis(),
        "storage": await _check_storage(),
    }
    failing = [name for name, ok in checks.items() if not ok]
    if not failing:
        status_value = "normal"
    elif len(failing) >= 2:
        status_value = "down"
    else:
        status_value = "degraded"
    return SystemStatusResponse(
        status=status_value,
        region=settings.deploy_region,
        node=settings.deploy_node,
        checks=checks,
    )


# ---------------------------------------------------------------------------
# Blog (public, marketing-side)
# ---------------------------------------------------------------------------


def _estimate_reading_minutes(markdown: str) -> int:
    """Rough reading-time estimate. Matches the `reading-time` package the
    web app uses (≈200 wpm). Floor-of-1 so a stub post still reads as a
    real piece of content.
    """
    words = len(markdown.split())
    return max(1, round(words / 200))


async def _serialize_public(
    post: BlogPost,
    storage: StorageBackend,
    *,
    include_content: bool,
) -> BlogPostPublicRead:
    bucket = get_attachments_bucket()
    cover_url = await storage.presigned_get_url(
        post.cover_image_key,
        f"{post.slug}-cover",
        disposition="inline",
        bucket=bucket,
    )
    body: str | None = None
    reading_min = 1
    if include_content:
        try:
            body = await _fetch_content(storage, post.content_key, bucket)
            reading_min = _estimate_reading_minutes(body)
        except Exception:
            logger.exception(
                "public_blog_content_fetch_failed post_id=%s", post.id
            )
            body = ""
    else:
        reading_min = max(1, len(post.description.split()) // 200)
    return BlogPostPublicRead(
        slug=post.slug,
        locale=post.locale,
        title=post.title,
        description=post.description,
        author=post.author,
        tags=list(post.tags or []),
        published_at=post.published_at,
        cover_image_url=cover_url,
        content=body,
        reading_time_minutes=reading_min,
    )


def _validate_public_locale(locale: str) -> None:
    if locale not in BLOG_LOCALES:
        from fastapi import HTTPException
        raise HTTPException(status_code=400, detail="BLOG_LOCALE_INVALID")


@router.get(
    "/blog/posts",
    response_model=list[BlogPostPublicRead],
)
async def public_list_blog_posts(
    response: Response,
    session: AsyncSession = Depends(get_async_session),
    storage: StorageBackend = Depends(get_storage),
    locale: str = "en",
) -> list[BlogPostPublicRead]:
    """Marketing-site list. Returns only published, non-deleted posts.

    Cached for 60s at the edge — new posts in the admin tool appear within
    a minute on /blog. Cover URLs are freshly presigned per request; their
    TTL is enforced by the storage backend (default 15 min).
    """
    _validate_public_locale(locale)
    stmt = (
        select(BlogPost)
        .where(
            BlogPost.locale == locale,
            BlogPost.status == BlogPostStatus.published,
            BlogPost.deleted_at.is_(None),
        )
        .order_by(BlogPost.published_at.desc())
    )
    rows = list((await session.execute(stmt)).scalars())
    response.headers["Cache-Control"] = "public, max-age=60"
    return [
        await _serialize_public(p, storage, include_content=False) for p in rows
    ]


@router.get(
    "/blog/posts/{slug}",
    response_model=BlogPostPublicRead,
)
async def public_get_blog_post(
    slug: str,
    response: Response,
    session: AsyncSession = Depends(get_async_session),
    storage: StorageBackend = Depends(get_storage),
    locale: str = "en",
) -> BlogPostPublicRead:
    """Marketing-site detail. 404s on unknown slug, draft, or deleted. The
    web app falls back to the in-repo MDX reader if this 404s, so an unknown
    slug here is not necessarily a real not-found.
    """
    _validate_public_locale(locale)
    stmt = select(BlogPost).where(
        BlogPost.slug == slug,
        BlogPost.locale == locale,
        BlogPost.status == BlogPostStatus.published,
        BlogPost.deleted_at.is_(None),
    )
    post = (await session.execute(stmt)).scalar_one_or_none()
    if post is None:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail="BLOG_POST_NOT_FOUND")
    response.headers["Cache-Control"] = "public, max-age=60"
    return await _serialize_public(post, storage, include_content=True)
