import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildCssVariables, darkTheme, lightTheme } from '../dist/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'dist', 'tokens.css');

// `#2c5697` -> `44 86 151`. Returns null for non-hex values (those get no
// companion). Emitting the channel form alongside each token is what lets the
// Tailwind config use `rgb(var(--x-rgb) / <alpha-value>)` so /opacity modifiers
// (bg-primary/5, ring-primary/30, …) actually compile.
function hexToChannels(value) {
  const m = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(String(value).trim());
  if (!m) return null;
  let h = m[1];
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  return `${r} ${g} ${b}`;
}

function block(selector, theme, scheme) {
  const vars = buildCssVariables(theme);
  const lines = Object.entries(vars)
    .flatMap(([name, value]) => {
      const decls = [`  ${name}: ${value};`];
      const channels = hexToChannels(value);
      if (channels) decls.push(`  ${name}-rgb: ${channels};`);
      return decls;
    })
    .join('\n');
  return `${selector} {\n${lines}\n  color-scheme: ${scheme};\n}`;
}

const css = [
  '/* Generated by @bimdossier/design-tokens — do not edit. */',
  block(':root', lightTheme, 'light'),
  block("[data-theme='dark']", darkTheme, 'dark'),
  '',
].join('\n\n');

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, css, 'utf8');
console.log(`wrote ${outPath}`);
