import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildCssVariables, darkTheme, lightTheme } from '../dist/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'dist', 'tokens.css');

function block(selector, theme, scheme) {
  const vars = buildCssVariables(theme);
  const lines = Object.entries(vars)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n');
  return `${selector} {\n${lines}\n  color-scheme: ${scheme};\n}`;
}

const css = [
  '/* Generated by @bimstitch/design-tokens — do not edit. */',
  block(':root', lightTheme, 'light'),
  block("[data-theme='dark']", darkTheme, 'dark'),
  '',
].join('\n\n');

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, css, 'utf8');
console.log(`wrote ${outPath}`);
