"""Add edges_storage_key to project_files.

Stores the S3 key for pre-computed edge geometry generated by the
processor worker, so the viewer can load edges directly instead of
computing them client-side.

Idempotent: guarded by `_column_exists`.

Revision ID: 0005_edges_storage_key
Revises: 0004_deadline_filing_fields
Create Date: 2026-06-10
"""

from __future__ import annotations

import os
from typing import TYPE_CHECKING

from alembic import op
from sqlalchemy import text

if TYPE_CHECKING:
    from collections.abc import Sequence

# Revision identifiers, used by Alembic.
revision: str = "0005_edges_storage_key"
down_revision: str | None = "0004_deadline_filing_fields"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _schema() -> str:
    schema = os.environ.get("BIMSTITCH_TENANT_SCHEMA")
    if not schema:
        raise RuntimeError("BIMSTITCH_TENANT_SCHEMA is required for tenant migrations")
    return schema


def _column_exists(bind, schema: str, table: str, column: str) -> bool:
    return (
        bind.execute(
            text(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = :s AND table_name = :t AND column_name = :c"
            ),
            {"s": schema, "t": table, "c": column},
        ).scalar()
        is not None
    )


def upgrade() -> None:
    bind = op.get_bind()
    schema = _schema()

    if not _column_exists(bind, schema, "project_files", "edges_storage_key"):
        bind.execute(
            text(
                f'ALTER TABLE "{schema}".project_files '
                "ADD COLUMN edges_storage_key varchar(512)"
            )
        )


def downgrade() -> None:
    bind = op.get_bind()
    schema = _schema()
    bind.execute(
        text(
            f'ALTER TABLE "{schema}".project_files '
            "DROP COLUMN IF EXISTS edges_storage_key"
        )
    )
