'use client';

import { Download, FileText } from '@bimdossier/ui/icons';
import { useTranslations } from 'next-intl';
import { useEffect, useRef, useState, type JSX } from 'react';
import { toast } from 'sonner';

import { Button, Spinner } from '@bimdossier/ui';

import { triggerBrowserDownload } from '@/lib/api/client';
import { downloadPooledFindingsCsv } from '@/lib/api/pooledFindings';
import { useAuth } from '@/providers/AuthProvider';

import { useGeneratePooledReport, usePooledReport } from './usePooledReports';

/**
 * Free-tier board exports. The paid `FindingsExportActions` pulls org-only
 * hooks (report generation, project permissions), so the free branch uses these
 * minimal buttons instead — CSV streams synchronously; the snag-list PDF is
 * generated by the processor (create → poll → presigned download), reusing the
 * paid snag-list pipeline server-side.
 */
export function PooledFindingsExportButton({
  projectId,
  canGeneratePdf = true,
}: {
  projectId: string;
  canGeneratePdf?: boolean;
}): JSX.Element {
  const t = useTranslations('findingsBoard.export');
  const { tokens } = useAuth();
  const accessToken = tokens?.access_token;
  const [pending, setPending] = useState(false);
  const [reportId, setReportId] = useState<string | null>(null);

  const generate = useGeneratePooledReport(projectId);
  const report = usePooledReport(projectId, reportId);
  // One download/toast per generated report, even though polling re-renders.
  const handledReportId = useRef<string | null>(null);

  useEffect(() => {
    const data = report.data;
    if (reportId === null || data === undefined) return;
    if (handledReportId.current === reportId) return;
    if (data.status === 'ready' && data.download_url !== null) {
      handledReportId.current = reportId;
      setReportId(null);
      // Presigned URL — a plain navigation download (an auth header would break
      // the S3 signature, same reason as `putRaw`).
      window.location.assign(data.download_url);
    } else if (data.status === 'failed') {
      handledReportId.current = reportId;
      setReportId(null);
      toast.error(t('pdfError'));
    }
  }, [report.data, reportId, t]);

  const handleCsv = async (): Promise<void> => {
    if (accessToken === undefined) return;
    setPending(true);
    try {
      const { blob, filename } = await downloadPooledFindingsCsv(accessToken, projectId);
      triggerBrowserDownload(blob, filename ?? `findings-${projectId}.csv`);
    } catch {
      toast.error(t('csvError'));
    } finally {
      setPending(false);
    }
  };

  const handlePdf = (): void => {
    generate.mutate(undefined, {
      onSuccess: (created) => {
        handledReportId.current = null;
        setReportId(created.id);
      },
      onError: () => {
        toast.error(t('pdfError'));
      },
    });
  };

  const pdfBusy = generate.isPending || reportId !== null;

  return (
    <>
      <Button
        variant="border"
        size="md"
        className="shrink-0 whitespace-nowrap"
        disabled={pending || accessToken === undefined}
        onClick={() => { void handleCsv(); }}
      >
        {pending ? (
          <Spinner size="md" className="mr-1.5 h-3 w-3 text-current" />
        ) : (
          <Download className="mr-1.5 h-3 w-3" />
        )}
        {t('csv')}
      </Button>
      {canGeneratePdf && (
        <Button
          variant="border"
          size="md"
          className="shrink-0 whitespace-nowrap"
          disabled={pdfBusy || accessToken === undefined}
          onClick={handlePdf}
        >
          {pdfBusy ? (
            <Spinner size="md" className="mr-1.5 h-3 w-3 text-current" />
          ) : (
            <FileText className="mr-1.5 h-3 w-3" />
          )}
          {pdfBusy ? t('pdfPreparing') : t('pdf')}
        </Button>
      )}
    </>
  );
}
