"""Public, unauthenticated endpoints for the marketing + login surfaces.

These are explicitly carved out from the rest of the app:

- `GET /public/projects-map` — anonymized, aggregated project locations
  for the pre-login NL map. RLS is bypassed (the request has no tenant
  context); we only return city / averaged lat-lng / count so no tenant
  data leaks.

- `GET /public/system-status` — live platform health for the login page
  status badge and KPI strip. Pings DB + Redis + MinIO HEAD; degrades on
  the first failure but always returns a payload so the page never errors.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, Depends, Response
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

from bimstitch_api.approx import approx_count_floor
from bimstitch_api.cache.client import get_redis
from bimstitch_api.config import Settings, get_settings
from bimstitch_api.db import get_async_session
from bimstitch_api.models.organization import Organization, OrganizationStatus
from bimstitch_api.schemas.public import (
    ProjectsMapPoint,
    SystemStatusResponse,
)
from bimstitch_api.storage import get_storage

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/public", tags=["public"])


@router.get("/projects-map", response_model=list[ProjectsMapPoint])
async def projects_map(
    response: Response,
    session: AsyncSession = Depends(get_async_session),
) -> list[ProjectsMapPoint]:
    """Aggregate non-removed, geo-located projects by city across all tenants.

    Pre-login endpoint with no tenant context. Under schema-per-tenant the
    rows live in `org_<hex>.projects`, so we UNION ALL the geo columns from
    every active org schema and aggregate in an outer query. Only anonymized
    fields cross the wire (city + averaged lat/lng + floored count).

    `lifecycle_state` is a per-schema enum type; we filter it inside each
    subquery and project only schema-agnostic columns so the UNION's column
    types unify cleanly. Per-city counts are floored to one significant
    figure via `approx_count_floor` so exact tenant numbers never leak.
    Cached for one minute at the CDN edge.
    """
    schemas_stmt = select(Organization.schema_name).where(
        Organization.status.in_(
            (OrganizationStatus.active, OrganizationStatus.suspended)
        ),
        Organization.deleted_at.is_(None),
    )
    schemas = (await session.execute(schemas_stmt)).scalars().all()

    response.headers["Cache-Control"] = "public, max-age=60"
    if not schemas:
        return []

    # schema_name is generated by schema_name_for() as `org_<32 hex>` — not
    # user input, safe to interpolate.
    union_parts = [
        f'SELECT city, latitude, longitude, id FROM "{s}".projects '
        f"WHERE lifecycle_state <> 'removed' "
        f"AND latitude IS NOT NULL AND longitude IS NOT NULL AND city IS NOT NULL"
        for s in schemas
    ]
    sql = (
        "SELECT city, AVG(latitude) AS lat, AVG(longitude) AS lng, "
        "COUNT(id) AS count FROM ("
        + " UNION ALL ".join(union_parts)
        + ") AS all_projects GROUP BY city"
    )
    rows = (await session.execute(text(sql))).all()
    return [
        ProjectsMapPoint(
            city=row.city,
            lat=float(row.lat),
            lng=float(row.lng),
            count=approx_count_floor(int(row.count)),
        )
        for row in rows
    ]


async def _check_db(session: AsyncSession) -> bool:
    try:
        await session.execute(select(1))
        return True
    except Exception:
        logger.warning("system-status DB check failed", exc_info=True)
        return False


async def _check_redis() -> bool:
    try:
        await get_redis().ping()
        return True
    except Exception:
        logger.warning("system-status Redis check failed", exc_info=True)
        return False


async def _check_storage() -> bool:
    try:
        await get_storage().ensure_bucket()
        return True
    except Exception:
        logger.warning("system-status storage check failed", exc_info=True)
        return False


@router.get("/system-status", response_model=SystemStatusResponse)
async def system_status(
    session: AsyncSession = Depends(get_async_session),
    settings: Settings = Depends(get_settings),
) -> SystemStatusResponse:
    checks = {
        "db": await _check_db(session),
        "redis": await _check_redis(),
        "storage": await _check_storage(),
    }
    failing = [name for name, ok in checks.items() if not ok]
    if not failing:
        status_value = "normal"
    elif len(failing) >= 2:
        status_value = "down"
    else:
        status_value = "degraded"
    return SystemStatusResponse(
        status=status_value,
        region=settings.deploy_region,
        node=settings.deploy_node,
        checks=checks,
    )
