#!/usr/bin/env python3
"""Generate every favicon / app-icon / PWA / mobile / in-app brand asset from the
master logo at assets/logos/BD_W_bg.png.

Master = BD_W_bg.png (the full blue square — "the one"). The transparent white glyph
BD_W.png is used only where a layered/transparent mark is structurally required:
Android adaptive-icon foreground + monochrome layers, the splash logo, and maskable
PWA icons (which need extra safe-zone padding so a circular mask never clips the
letters).

Run from the repo root:  python scripts/generate-brand-icons.py
Idempotent — safe to re-run. Requires Pillow.
"""

from __future__ import annotations

import base64
import io
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MASTER_BG = os.path.join(ROOT, "assets", "logos", "BD_W_bg.png")  # blue square
MASTER_GLYPH = os.path.join(ROOT, "assets", "logos", "BD_W.png")  # transparent white BD

# Brand blue = the master's center pixel = #2c5697.
BRAND_BLUE = (44, 86, 151, 255)
TRANSPARENT = (0, 0, 0, 0)

_bg = Image.open(MASTER_BG).convert("RGBA")
_glyph = Image.open(MASTER_GLYPH).convert("RGBA")


def full_bleed(size: int) -> Image.Image:
    """The blue square logo resized as-is."""
    return _bg.resize((size, size), Image.LANCZOS)


def glyph_on_canvas(size: int, frac: float, bg: tuple[int, int, int, int]) -> Image.Image:
    """White BD glyph scaled to `frac` of the canvas, centered on `bg`."""
    canvas = Image.new("RGBA", (size, size), bg)
    gs = max(1, round(size * frac))
    g = _glyph.resize((gs, gs), Image.LANCZOS)
    off = (size - gs) // 2
    canvas.alpha_composite(g, (off, off))
    return canvas


def png_bytes(img: Image.Image) -> bytes:
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def write_png(rel: str, img: Image.Image) -> None:
    path = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    img.save(path, format="PNG")
    print(f"  png  {rel}  ({img.width}x{img.height})")


def write_ico(rel: str) -> None:
    path = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    full_bleed(256).save(path, format="ICO", sizes=[(16, 16), (32, 32), (48, 48)])
    print(f"  ico  {rel}  (16/32/48)")


def write_svg_wrapper(rel: str, inner: Image.Image, size: int = 512) -> None:
    """SVG that embeds the raster as a data-URI (keeps the manifest's svg+xml entries
    valid while rendering the exact logo art)."""
    path = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    b64 = base64.b64encode(png_bytes(inner)).decode("ascii")
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" '
        f'viewBox="0 0 {size} {size}" role="img" aria-label="BimDossier">'
        f'<image width="{size}" height="{size}" '
        f'href="data:image/png;base64,{b64}"/></svg>\n'
    )
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(svg)
    print(f"  svg  {rel}")


def write_brand_asset(rel: str) -> None:
    """TS module exporting the brand mark as self-contained base64 data-URIs for the
    shared @bimstitch/brand package (it can't import an app's public asset / a .png).

    - BRAND_MARK_DATA_URI: the full blue square ("the one") — for headers/footers/panes.
    - BRAND_GLYPH_WHITE_DATA_URI: transparent white "BD" glyph — for blue/dark surfaces
      where a blue square would be blue-on-blue (e.g. the portal sidebar)."""
    path = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    square_b64 = base64.b64encode(png_bytes(full_bleed(256))).decode("ascii")
    glyph_b64 = base64.b64encode(
        png_bytes(glyph_on_canvas(256, 0.92, TRANSPARENT))
    ).decode("ascii")
    content = (
        "// Auto-generated by scripts/generate-brand-icons.py — do not edit by hand.\n"
        "// The BimDossier 'BD' brand mark as self-contained data-URIs so the shared\n"
        "// package renders the real logo art across every consuming app.\n"
        "\n"
        "/** The full blue square logo ('the one') — for light/dark headers, footers, panes. */\n"
        "export const BRAND_MARK_DATA_URI =\n"
        f"  'data:image/png;base64,{square_b64}';\n"
        "\n"
        "/** Transparent white 'BD' glyph — for blue/dark surfaces (e.g. the sidebar chip). */\n"
        "export const BRAND_GLYPH_WHITE_DATA_URI =\n"
        f"  'data:image/png;base64,{glyph_b64}';\n"
    )
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    print(f"  ts   {rel}")


def main() -> None:
    print("apps/web:")
    write_png("apps/web/src/app/icon.png", full_bleed(512))
    write_png("apps/web/src/app/apple-icon.png", full_bleed(180))
    write_ico("apps/web/src/app/favicon.ico")
    write_png("apps/web/public/icon-192.png", full_bleed(192))
    write_png("apps/web/public/icon-512.png", full_bleed(512))

    print("apps/portal:")
    write_png("apps/portal/public/icon-192.png", full_bleed(192))
    write_png("apps/portal/public/icon-512.png", full_bleed(512))
    write_png("apps/portal/public/icon-maskable-192.png", glyph_on_canvas(192, 0.62, BRAND_BLUE))
    write_png("apps/portal/public/icon-maskable-512.png", glyph_on_canvas(512, 0.62, BRAND_BLUE))
    write_svg_wrapper("apps/portal/public/icon.svg", full_bleed(512))
    write_svg_wrapper("apps/portal/public/icon-maskable.svg", glyph_on_canvas(512, 0.62, BRAND_BLUE))
    write_png("apps/portal/src/app/apple-icon.png", full_bleed(180))
    write_ico("apps/portal/src/app/favicon.ico")

    print("apps/mobile:")
    write_png("apps/mobile/assets/images/icon.png", full_bleed(1024))
    write_png("apps/mobile/assets/images/favicon.png", full_bleed(48))
    write_png(
        "apps/mobile/assets/images/android-icon-foreground.png",
        glyph_on_canvas(512, 0.60, TRANSPARENT),
    )
    write_png(
        "apps/mobile/assets/images/android-icon-background.png",
        Image.new("RGBA", (512, 512), BRAND_BLUE),
    )
    write_png(
        "apps/mobile/assets/images/android-icon-monochrome.png",
        glyph_on_canvas(432, 0.60, TRANSPARENT),
    )
    write_png(
        "apps/mobile/assets/images/splash-icon.png",
        glyph_on_canvas(512, 0.72, TRANSPARENT),
    )

    print("packages/brand:")
    write_brand_asset("packages/brand/src/brandMarkAsset.ts")

    print("Done.")


if __name__ == "__main__":
    main()
