"""0001_initial_schema

Revision ID: 8db173087044
Revises: 
Create Date: 2026-05-03 11:03:34.811557
"""
from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from bimstitch_api._rls_sql import (
    create_app_role_statements,
    disable_rls_statements,
    enable_rls_statements,
)

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('contractors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kvk_number', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_contractors_org_name')
    )
    op.create_index('ix_contractors_organization_id', 'contractors', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('reference_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('planning', 'ontwerp', 'vergunning', 'uitvoering', 'oplevering', 'gereed', 'on_hold', name='projectstatus'), server_default='planning', nullable=False),
    sa.Column('lifecycle_state', sa.Enum('active', 'archived', 'removed', name='projectlifecyclestate'), server_default='active', nullable=False),
    sa.Column('phase', sa.Enum('ontwerp', 'bestek', 'werkvoorbereiding', 'ruwbouw', 'afbouw', 'oplevering', name='projectphase'), server_default='ontwerp', nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=7), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('municipality', sa.String(length=255), nullable=True),
    sa.Column('bag_id', sa.String(length=50), nullable=True),
    sa.Column('permit_number', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_projects_org_name')
    )
    op.create_index('ix_projects_contractor_id', 'projects', ['contractor_id'], unique=False)
    op.create_index('ix_projects_lifecycle_state', 'projects', ['lifecycle_state'], unique=False)
    op.create_index('ix_projects_organization_id', 'projects', ['organization_id'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_index('uq_projects_org_reference_code', 'projects', ['organization_id', 'reference_code'], unique=True, postgresql_where='reference_code IS NOT NULL')
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('discipline', sa.Enum('architectural', 'structural', 'mep', 'coordination', 'other', name='modeldiscipline'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='modelstatus'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_models_project_name')
    )
    op.create_index('ix_models_project_id', 'models', ['project_id'], unique=False)
    op.create_index('ix_models_status', 'models', ['status'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='projectrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_index('ix_project_members_user_id', 'project_members', ['user_id'], unique=False)
    op.create_index('uq_one_owner_per_project', 'project_members', ['project_id'], unique=True, postgresql_where=sa.text("role = 'owner'"))
    op.create_table('project_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('ifc', 'pdf', name='filetype'), server_default='ifc', nullable=False),
    sa.Column('ifc_schema', sa.Enum('IFC2X3', 'IFC4', 'IFC4X1', 'IFC4X3', 'unknown', name='ifcschema'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'ready', 'rejected', name='projectfilestatus'), server_default='pending', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.Enum('not_started', 'queued', 'running', 'succeeded', 'failed', name='extractionstatus'), server_default='not_started', nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('extraction_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extractor_version', sa.String(length=64), nullable=True),
    sa.Column('fragments_storage_key', sa.String(length=512), nullable=True),
    sa.Column('metadata_storage_key', sa.String(length=512), nullable=True),
    sa.Column('properties_storage_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='ck_project_files_size_nonneg'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version_number', name='uq_project_files_model_version'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_project_files_extraction_status', 'project_files', ['extraction_status'], unique=False)
    op.create_index('ix_project_files_file_type', 'project_files', ['file_type'], unique=False)
    op.create_index('ix_project_files_model_id', 'project_files', ['model_id'], unique=False)
    op.create_index('ix_project_files_status_created_at', 'project_files', ['status', 'created_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.Enum('ifc_extraction', 'pdf_extraction', 'verification', 'batch_update', 'bbl_compliance_check', 'wkb_compliance_check', 'compliance_check', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'started', 'running', 'succeeded', 'failed', name='jobstatus'), server_default='pending', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['project_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_file_id', 'jobs', ['file_id'], unique=False, postgresql_where=sa.text('file_id IS NOT NULL'))
    op.create_index('ix_jobs_job_type', 'jobs', ['job_type'], unique=False)
    op.create_index('ix_jobs_org_created_at', 'jobs', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_jobs_organization_id', 'jobs', ['organization_id'], unique=False)
    op.create_index('ix_jobs_project_id', 'jobs', ['project_id'], unique=False, postgresql_where=sa.text('project_id IS NOT NULL'))
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###

    for stmt in create_app_role_statements():
        op.execute(stmt)
    for stmt in enable_rls_statements():
        op.execute(stmt)


def downgrade() -> None:
    for stmt in disable_rls_statements():
        op.execute(stmt)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_project_id', table_name='jobs', postgresql_where=sa.text('project_id IS NOT NULL'))
    op.drop_index('ix_jobs_organization_id', table_name='jobs')
    op.drop_index('ix_jobs_org_created_at', table_name='jobs')
    op.drop_index('ix_jobs_job_type', table_name='jobs')
    op.drop_index('ix_jobs_file_id', table_name='jobs', postgresql_where=sa.text('file_id IS NOT NULL'))
    op.drop_table('jobs')
    op.drop_index('ix_project_files_status_created_at', table_name='project_files')
    op.drop_index('ix_project_files_model_id', table_name='project_files')
    op.drop_index('ix_project_files_file_type', table_name='project_files')
    op.drop_index('ix_project_files_extraction_status', table_name='project_files')
    op.drop_table('project_files')
    op.drop_index('uq_one_owner_per_project', table_name='project_members', postgresql_where=sa.text("role = 'owner'"))
    op.drop_index('ix_project_members_user_id', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('ix_models_status', table_name='models')
    op.drop_index('ix_models_project_id', table_name='models')
    op.drop_table('models')
    op.drop_index('uq_projects_org_reference_code', table_name='projects', postgresql_where='reference_code IS NOT NULL')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_organization_id', table_name='projects')
    op.drop_index('ix_projects_lifecycle_state', table_name='projects')
    op.drop_index('ix_projects_contractor_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_contractors_organization_id', table_name='contractors')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
